server:
  port: 8001
spring:
  application:
    name: order-server
  cloud:
    config:
      enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
