server:
  port: 8000
spring:
  application:
    name: user-server
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_tcc_user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: liminpoint123456
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
